export const DEFAULT_PREFIX = 'SIGNALR';

// Library dispatched action types.
export const ON_CONFERENCE_JOINED = 'ON_CONFERENCE_JOINED';
export const ON_CONFERENCE_JOIN_FAILED = 'ON_CONFERENCE_JOIN_FAILED';
export const ON_CONFERENCE_CONNECTION_CLOSED = 'ON_CONFERENCE_JOIN_CLOSED';
export const ON_CONFERENCE_RECONNECTING = 'ON_CONFERENCE_RECONNECTING';
export const ON_CONFERENCE_RECONNECTED = 'ON_CONFERENCE_RECONNECTED';

// User dispatched action types.
export const CONFERENCE_JOIN = 'JOIN_CONFERENCE';
export const SUBSCRIBE_EVENT = 'SUBSCRIBE_EVENT';
export const SEND = 'SEND';
export const CLOSE = 'CLOSE';
